INSERT INTO barang (KODE_BRG, NAMA_BRG, HARGA_BRG, STOK) VALUE ('B006', 'TOPI', 88, 99);

INSERT INTO barang 
(KODE_BRG, NAMA_BRG) 
VALUE 
('B007', 'SEPATU');

INSERT INTO barang 
(KODE_BRG, STOK)
VALUE 
('B008', '6');


DELETE 
FROM barang
WHERE NAMA_BRG = 'KAOS';

INSERT INTO barang
VALUE
('B009', 'Gun', 99, 100)

UPDATE barang
SET  HARGA_BRG = 40000
WHERE NAMA_BRG = 'TOPI'

UPDATE barang
SET  HARGA_BRG = 90000
WHERE STOK < 4 AND NAMA_BRG = 'TOPI'

INSERT INTO barang
(NAMA_BRG, HARGA_BRG)
VALUE
('Horse', 80)

DELETE 
FROM barang
WHERE NAMA_BRG = 'SEPATU'

UPDATE barang
SET STOK = '4'
WHERE KODE_BRG = 'B006'

